### PR TITLE
Update paper.md -- fix affiliation issues

### PR DESCRIPTION
**Pull request by thierrymoudiki**
@arfon fixed affiliation formatting issues

### CODE REVIEW

**Comment by thierrymoudiki** [comment]
@arfon Fixed bibliography "issues"

**Comment by arfon** [comment]
:+1: looks good. Please merge.

**Comment by thierrymoudiki** [comment]
@arfon done! Anything wrong with affiliation formatting?

**Comment by arfon** [comment]
Looks like it's fixed now: https://github.com/openjournals/joss-reviews/issues/6477#issuecomment-1997169161

**Comment by thierrymoudiki** [comment]
Cool

**Pull request merged**
